name: Build & Test

on:
  push:
    branches: []
    pull_request: []
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Build
        run: |
          find . -name '*.rb' -exec brew install {} +

      - name: Test
        run: |
          find . -name '*.rb' -exec brew test {} +
